SRC_DIR = # Le répertoire contenant les fichiers sources.
SRC= # Les sources.
OBJ_DIR = # Le répertoire contenant les fichiers sources.
OBJ= # Les fichiers objets (fichiers compilés).
TEST= # Le nom de l'exécutable pour tester la bibliothèque.
CC=gcc # Le compilateur.
FLAGS= # Les options du compilateur.
LIBS= # Les librairies (s'il y en a).

%.o: %.c
    $(CC) ...