SRC= # Les sources.
OBJ= # Les fichiers objets (fichiers compilés).
TEST= # Le nom de l'exécutable pour tester la bibliothèque.
CC=gcc # Le compilateur.
FLAGS= -std=c99 # Les options du compilateur.
LIBS= # Les librairies (s'il y en a).

%.o: %.c
    $(CC) ...